### ISSUE TITLE
Document Ref methods

### ISSUE THREAD

**Issue by GustavoRFS** [akcyp/react-lasso-select#5]
I needed a method to reset the selection when the last point connects with another, but i didn't find it at docs. I had to debug the code and I found the dispatchPathAction({type: "RESET"}) method to reset the selection.

Pls, write full docs from ref

**Comment by akcyp** [comment]
Possible duplicate of: issue https://github.com/akcyp/react-lasso-select/issues/3
You should operate on the value attribute. You may be interested in the following example: https://codesandbox.io/s/react-lasso-select-issue-2-forked-9nz9vh
